foreground #fcdbd6
background #1f0f0d
cursor #ffb4a8
cursor_text_color #690000
selection_background #8b2117
selection_foreground #ffdcd7

color0 #1f0f0d
color1 #ffb4ab
color2 #ffb4a8
color3 #f5bd64
color4 #ffb4a8
color5 #c10404
color6 #815700
color7 #fcdbd6

color8 #ad8882
color9 #ffb4ab
color10 #ffb4a8
color11 #f5bd64
color12 #ffb4a8
color13 #c10404
color14 #815700
color15 #e7bdb6
